FROM python:3.12

LABEL maintainer=["Muhammad Ahmad <ahmadshaukat_4@outlook.com>"]

WORKDIR /code
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    portaudio19-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry
COPY . /code/
RUN poetry config virtualenvs.create false
RUN poetry install
EXPOSE 8000

CMD ["sh", "-c", "poetry run uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --reload"]